# Generated by Django 5.0.6 on 2024-05-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgresbd', '0002_cake'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rewiew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=70)),
                ('name', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
