# Generated by Django 5.0.6 on 2024-05-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgresbd', '0003_rewiew'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='image',
            field=models.ImageField(blank=True, upload_to='swetty-kitty/src/assets'),
        ),
    ]
